spring.application.name=ms-campuslab-catalog

server.port=${SERVER_PORT:8082}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/campuslab_catalog}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:123456}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}